defaults:
  - data: mtg64
  - framework: sivae
  - run_location: default

settings:
  job:
    seed: 777
  data:
    batch_size: 32

trainer:
  _target_: pytorch_lightning.Trainer
#  cpus: 2
  gpus: 1  # why does this crash?
#  strategy: ddp_spawn
  max_steps: 1000
  max_epochs: 1000
  callbacks:
    - _target_: mtg_ml.util.ptl.VisualiseCallback
      name: 'vis'
      input_batch: 16
      every_n_steps: 100
      log_local: FALSE
      log_wandb: FALSE
      save_dir: .
      mean_std:
        - ${data.meta.img_mean}
        - ${data.meta.img_std}
      figwidth: 15
