defaults:
  - data: mtg64
  - framework: basic_denoiser
  - run_location: default

settings:
  job:
    seed: 777
  data:
    batch_size: 16

trainer:
  _target_: pytorch_lightning.Trainer
  gpus: 1
#  num_nodes: 1
#  strategy: ddp_spawn
  max_steps: 1000
  max_epochs: 1000
  callbacks:
    - _target_: mtg_ml.util.ptl.VisualiseCallback
      name: 'vis'
      input_batch: 100
      every_n_steps: 500
      log_local: FALSE
      log_wandb: FALSE
      save_dir: .
      mean_std:
        - ${data.meta.img_mean}
        - ${data.meta.img_std}
      figwidth: 15
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      dirpath: .
      monitor: NULL
      every_n_train_steps: 1000
      verbose: True
      save_top_k: -1
