name: sivae

system_cls:
  _target_: mtg_ml.framework.SoftIntroVaeSystem
  # model
  z_size: 256
  # training
  lr_enc: 2e-4
  lr_dec: 2e-4
  recon_loss: "mse"
  # loss scaling
  beta_kl: 1.0
  beta_rec: 1.0  # don't really adjust this
  beta_neg: 1024.0
  gamma_r: 1e-8
  # dataset_settings:
  img_size: ${data.meta.img_size}
  img_chn: ${data.meta.img_chn}
  conv_channels: [32, 64, 128, 256, 512, 512]
  # unimplemented:
  # exit_on_negative_diff: bool = False,  # TODO: implement
  # training_measure_fid: bool = False,   # TODO: implement
